@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
show member

Class RankCommand
interface "<<Client>>\nComparator" as Comparator
Class Client {
- totalPurchase : int
}

Class Name

Class CommandResult

class TotalPurchaseComparator {
+ {static} COMPARATOR_WORD : String = "total"
}

class NameComparator {
+ {static} COMPARATOR_WORD : String = "name"
}

RankCommand ..> CommandResult : > creates
RankCommand --> "1" Comparator : ranks clients with >
TotalPurchaseComparator .up.|> Comparator
NameComparator .up.|> Comparator

TotalPurchaseComparator ..> Client
NameComparator ..> Client

Client -d-> "1" Name : has >








@enduml